server:
  port: 9603

#微服务配置
spring:
  redis:
    host: 192.168.71.138
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.71.138:8848
  application:
    name: service-makeAppointment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.138:3306/dxssmjj?serverTimezone=Asia/Shanghai
    username: root
    password: 974955

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml