server:
  port: 9605


spring:
  redis:
    host: 192.168.71.138
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: service-oss
  servlet:
    multipart:
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.71.138:8848
aliyun:
  oss:
    bucketName: dxssmjj
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tJej914Y4tAMJDVt1eh
    secret: o082qXcgCpX64eLxfrBd4pTzmrZCws